// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq4c7bAkK8pXp0LCOtOOOheml--CzHwEc',
    appId: '1:993548271108:web:204cceb3b03f0a54c23f51',
    messagingSenderId: '993548271108',
    projectId: 'riverpod-firestore-strea-db616',
    authDomain: 'riverpod-firestore-strea-db616.firebaseapp.com',
    storageBucket: 'riverpod-firestore-strea-db616.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvrTvOakAH3I7x4GUCp5oJCfYGp0OfruA',
    appId: '1:993548271108:android:5e4f62358bb5f894c23f51',
    messagingSenderId: '993548271108',
    projectId: 'riverpod-firestore-strea-db616',
    storageBucket: 'riverpod-firestore-strea-db616.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm9F1RVzTbUC_ZDmDfrVAdl6DiDt-8YpM',
    appId: '1:993548271108:ios:a3108bf9d10cb9a9c23f51',
    messagingSenderId: '993548271108',
    projectId: 'riverpod-firestore-strea-db616',
    storageBucket: 'riverpod-firestore-strea-db616.appspot.com',
    iosClientId: '993548271108-paic7mci95f82cjpq1v7k7gq291ehqfe.apps.googleusercontent.com',
    iosBundleId: 'shop.mtcoding.riverpodFirestoreStream',
  );
}
